mklink /J .\runtime\libtorch\api .\runtime\core\api 
mklink /J .\runtime\libtorch\bin .\runtime\core\bin
mklink /J .\runtime\libtorch\cmake .\runtime\core\cmake
mklink /J .\runtime\libtorch\decoder .\runtime\core\decoder
mklink /J .\runtime\libtorch\frontend .\runtime\core\frontend
mklink /J .\runtime\libtorch\grpc .\runtime\core\grpc
mklink /J .\runtime\libtorch\http .\runtime\core\http
mklink /J .\runtime\libtorch\kaldi .\runtime\core\kaldi
mklink /J .\runtime\libtorch\patch .\runtime\core\patch
mklink /J .\runtime\libtorch\post_processor .\runtime\core\post_processor
mklink /J .\runtime\libtorch\test .\runtime\core\test
mklink /J .\runtime\libtorch\utils .\runtime\core\utils
mklink /J .\runtime\libtorch\websocket .\runtime\core\websocket